# Generated by Django 5.1 on 2025-07-23 16:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=20, unique=True)),
                ('case_type', models.CharField(choices=[('vmer', 'VMER'), ('dc_visit', 'DC Visit'), ('online', 'Online')], max_length=20)),
                ('policy_type', models.CharField(choices=[('new', 'New'), ('revival', 'Revival')], max_length=20)),
                ('policy_number', models.CharField(blank=True, max_length=30, null=True)),
                ('sum_assured', models.DecimalField(decimal_places=2, max_digits=12)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')], max_length=10)),
                ('due_date', models.DateField()),
                ('payment_method', models.CharField(blank=True, choices=[('lic', 'LIC'), ('self', 'Self')], max_length=10, null=True)),
                ('holder_name', models.CharField(max_length=255)),
                ('holder_phone', models.CharField(max_length=15)),
                ('holder_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('lic_office_code', models.CharField(max_length=10)),
                ('assigned_coordinator_id', models.CharField(max_length=12)),
                ('created_by', models.CharField(max_length=12)),
                ('assigned_telecaller_id', models.CharField(blank=True, max_length=12, null=True)),
                ('assigned_dc_id', models.CharField(blank=True, max_length=12, null=True)),
                ('assigned_vmer_med_co_id', models.CharField(blank=True, max_length=12, null=True)),
                ('video_url', models.TextField(blank=True, null=True)),
                ('report_url', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('submitted_to_lic', 'Submitted to LIC'), ('completed', 'Completed')], default='created', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=20)),
                ('action_by', models.CharField(max_length=12)),
                ('action', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=20)),
                ('schedule_time', models.DateTimeField()),
                ('created_by', models.CharField(max_length=12)),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
