# Generated by Django 5.1 on 2025-07-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0002_diagnosticcenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('uploaded', 'Uploaded'), ('submitted_to_lic', 'Submitted to LIC'), ('completed', 'Completed')], default='created', max_length=20),
        ),
    ]
