# Generated by Django 5.1 on 2025-07-29 16:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0003_alter_case_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=12, unique=True)),
                ('test_name', models.CharField(max_length=255)),
                ('dc_charge', models.CharField(max_length=10)),
                ('lic_rural_charge', models.CharField(max_length=10)),
                ('lic_urban_charge', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
