# Generated by Django 5.1 on 2025-07-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0004_testdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='issue_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='issue_type',
            field=models.CharField(blank=True, choices=[('customer_not_visited', 'Customer Did Not Visit'), ('test_issue', 'Issue While Test'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('issue', 'Issue'), ('cancelled', 'Cancelled'), ('uploaded', 'Uploaded'), ('submitted_to_lic', 'Submitted to LIC'), ('completed', 'Completed')], default='created', max_length=20),
        ),
    ]
