# Generated by Django 5.1 on 2025-08-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0005_case_issue_reason_case_issue_type_alter_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('vmer', 'VMER'), ('dc_visit', 'DC Visit'), ('online', 'Online'), ('both', 'Both')], max_length=20),
        ),
    ]
