# Generated by Django 5.1 on 2025-08-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0007_case_case_stage_alter_case_case_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_stage',
            field=models.CharField(blank=True, choices=[('vmer', 'VMER'), ('dc_visit', 'DC Visit')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('vmer', 'VMER'), ('dc_visit', 'DC Visit'), ('online', 'Online'), ('both', 'Both')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
