# Generated by Django 5.1 on 2025-08-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0008_alter_case_case_stage_alter_case_case_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='schedule_type',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
