# Generated by Django 5.1 on 2025-08-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0009_schedule_schedule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_stage',
            field=models.CharField(blank=True, choices=[('vmer', 'VMER'), ('dc_visit', 'DC Visit')], default='vmer', max_length=20, null=True),
        ),
    ]
