# Generated by Django 5.1 on 2025-08-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0010_alter_case_case_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdetail',
            name='test_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
