# Generated by Django 5.1 on 2025-08-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0011_alter_testdetail_test_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='holder_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='holder_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='holder_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='holder_gender',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='holder_pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='holder_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='intimation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='lic_gst_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='lic_type',
            field=models.CharField(choices=[('urban', 'Urban'), ('rural', 'Rural')], default='urban', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='proposed_sum_insured',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='sum_insured_under_consideration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='tests',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='case',
            name='text_price',
            field=models.JSONField(default=dict),
        ),
    ]
