# Generated by Django 5.1 on 2025-08-26 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0012_case_holder_address_case_holder_city_case_holder_dob_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='text_price',
            new_name='test_price',
        ),
    ]
