# Generated by Django 5.1 on 2025-09-05 04:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0013_rename_text_price_case_test_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelecallerRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(blank=True, max_length=12, null=True)),
                ('telecaller_id', models.CharField(max_length=12)),
                ('remark', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
