# Generated by Django 5.1 on 2025-09-05 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0014_telecallerremark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='sum_assured',
        ),
    ]
