# Generated by Django 5.1 on 2025-09-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0015_remove_case_sum_assured'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='sum_assured',
            field=models.DecimalField(decimal_places=2, default=1.00, max_digits=12),
            preserve_default=False,
        ),
    ]
