# Generated by Django 5.1 on 2025-09-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0017_remove_case_sum_assured'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='lic_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
