# Generated by Django 5.1 on 2025-09-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0018_case_lic_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
