# Generated by Django 5.1 on 2025-10-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0019_case_special_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='lic_office_code',
            field=models.CharField(max_length=255),
        ),
    ]
