# Generated by Django 5.1.2 on 2025-11-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0021_insurancecompany_tataaigoffice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
