# Generated by Django 5.1 on 2025-08-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='development_officer_id',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='agent',
            name='lic_id',
            field=models.CharField(editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='branchoffice',
            name='divisional_office_id',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='branchoffice',
            name='lic_id',
            field=models.CharField(editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='developmentofficer',
            name='branch_office_id',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='developmentofficer',
            name='lic_id',
            field=models.CharField(editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='divisionaloffice',
            name='lic_id',
            field=models.CharField(editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='divisionaloffice',
            name='regional_office_id',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='headoffice',
            name='lic_id',
            field=models.CharField(editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='regionaloffice',
            name='head_office_id',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='regionaloffice',
            name='lic_id',
            field=models.CharField(editable=False, max_length=12, unique=True),
        ),
    ]
