# Generated by Django 5.1 on 2025-08-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetail', '0002_remove_user_city_remove_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hod', 'HOD'), ('coordinator', 'Coordinator'), ('telecaller', 'TeleCaller'), ('vmer_med_co', 'VmerMedCo'), ('diagnostic_center', 'DiagnosticCenter'), ('agent', 'Agent')], max_length=20),
        ),
    ]
