# Generated by Django 5.1 on 2025-11-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetail', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hod', 'HOD'), ('coordinator', 'Coordinator'), ('telecaller', 'TeleCaller'), ('vmer_med_co', 'VmerMedCo'), ('diagnostic_center', 'DiagnosticCenter'), ('agent', 'Agent'), ('accounts', 'Accounts')], max_length=20),
        ),
    ]
